# api/config/services.yaml
services:
    # ...
    'App\DataTransformer\ParkingDtoDataTransformer': ~
        # Uncomment only if autoconfiguration is disabled
        #tags: [ 'api_platform.data_transformer' ]
    
   
